/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb951",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2f0ed",
        "tertiary-fixed": "#ffddb3",
        "primary-fixed-dim": "#a4c9ff",
        "surface-container": "#efeeea",
        "on-tertiary-fixed-variant": "#633f00",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae8e4",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dbdad6",
        "primary-fixed": "#d4e3ff",
        "on-secondary-container": "#007146",
        "secondary-fixed-dim": "#7adaa3",
        "surface-container-low": "#f5f3ef",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#291800",
        "outline": "#727782",
        "background": "#fbf9f5",
        "surface-container-highest": "#e4e2de",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004884",
        "error": "#ba1a1a",
        "on-primary-container": "#003260",
        "on-background": "#1b1c1a",
        "surface": "#fbf9f5",
        "surface-bright": "#fbf9f5",
        "on-secondary-fixed-variant": "#005231",
        "on-tertiary-container": "#472c00",
        "on-secondary-fixed": "#002111",
        "tertiary": "#825500",
        "surface-variant": "#e4e2de",
        "surface-tint": "#075fab",
        "on-error": "#ffffff",
        "inverse-primary": "#a4c9ff",
        "secondary-container": "#93f3bb",
        "secondary": "#006d43",
        "tertiary-container": "#cd8d24",
        "primary": "#075fab",
        "on-primary-fixed": "#001c39",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c1c6d3",
        "primary-container": "#5d9cec",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#414751",
        "inverse-surface": "#30312e",
        "secondary-fixed": "#95f6be"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-xs": "4px",
        "stack-xxl": "64px",
        "stack-sm": "8px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "margin-desktop": "120px",
        "stack-md": "16px",
        "max-width": "1280px",
        "stack-lg": "24px",
        "stack-xl": "40px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
